name: sensor-reconstruction
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # Adjust depending on your CUDA version
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - tqdm
  - tensorboard
  - joblib
  - pip
  - pip:
      - protobuf  # Ensure compatibility with TensorBoard
